#!/bin/bash

# this is fine for 1 script, for multipe you only need 1 embed, then you link them. 
# There is an issue with initing the modules.
# make it 1 script if you can.

cython --embed /build/$PY_SCRIPT -o /build/$PY_SCRIPT.c 2>&1 | tee /build/cython.output


gcc /build/$PY_SCRIPT.c \
    -I /python/include/python2.7 \
    -L /python/lib \
    $(/python/bin/python2.7 /python/bin/python2.7-config --libs) \
    -pg \
    -fno-strict-aliasing \
    -g \
    -O2 \
    -DNDEBUG \
    -g \
    -fwrapv \
    -O3 \
    -Wall \
    -Wstrict-prototypes \
    -Wl,-no-export-dynamic -static -static-libgcc \
    -static -fPIC \
    -o /build/$PY_SCRIPT_OUTPUT \
    -v 2>&1 | tee /build/gcc.output